# import pytest
# from notes.utils import NotesError

# def test_given_message(self):
#     try:
#         dal;ds
#     except 